// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gettemperaturebyzipcode

import (
	"context"

	"github.com/dprio/cep-temperature/internal/domain/address"
	mock "github.com/stretchr/testify/mock"
)

// NewMockViaCEPGateway creates a new instance of MockViaCEPGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockViaCEPGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockViaCEPGateway {
	mock := &MockViaCEPGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockViaCEPGateway is an autogenerated mock type for the ViaCEPGateway type
type MockViaCEPGateway struct {
	mock.Mock
}

type MockViaCEPGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockViaCEPGateway) EXPECT() *MockViaCEPGateway_Expecter {
	return &MockViaCEPGateway_Expecter{mock: &_m.Mock}
}

// GetAddressByZipCode provides a mock function for the type MockViaCEPGateway
func (_mock *MockViaCEPGateway) GetAddressByZipCode(ctx context.Context, zipCode address.ZipCode) (*address.Address, error) {
	ret := _mock.Called(ctx, zipCode)

	if len(ret) == 0 {
		panic("no return value specified for GetAddressByZipCode")
	}

	var r0 *address.Address
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, address.ZipCode) (*address.Address, error)); ok {
		return returnFunc(ctx, zipCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, address.ZipCode) *address.Address); ok {
		r0 = returnFunc(ctx, zipCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*address.Address)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, address.ZipCode) error); ok {
		r1 = returnFunc(ctx, zipCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViaCEPGateway_GetAddressByZipCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAddressByZipCode'
type MockViaCEPGateway_GetAddressByZipCode_Call struct {
	*mock.Call
}

// GetAddressByZipCode is a helper method to define mock.On call
//   - ctx context.Context
//   - zipCode address.ZipCode
func (_e *MockViaCEPGateway_Expecter) GetAddressByZipCode(ctx interface{}, zipCode interface{}) *MockViaCEPGateway_GetAddressByZipCode_Call {
	return &MockViaCEPGateway_GetAddressByZipCode_Call{Call: _e.mock.On("GetAddressByZipCode", ctx, zipCode)}
}

func (_c *MockViaCEPGateway_GetAddressByZipCode_Call) Run(run func(ctx context.Context, zipCode address.ZipCode)) *MockViaCEPGateway_GetAddressByZipCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 address.ZipCode
		if args[1] != nil {
			arg1 = args[1].(address.ZipCode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockViaCEPGateway_GetAddressByZipCode_Call) Return(address1 *address.Address, err error) *MockViaCEPGateway_GetAddressByZipCode_Call {
	_c.Call.Return(address1, err)
	return _c
}

func (_c *MockViaCEPGateway_GetAddressByZipCode_Call) RunAndReturn(run func(ctx context.Context, zipCode address.ZipCode) (*address.Address, error)) *MockViaCEPGateway_GetAddressByZipCode_Call {
	_c.Call.Return(run)
	return _c
}
