// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gettemperaturebyzipcode

import (
	"context"

	"github.com/dprio/cep-temperature/internal/domain/weather"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWeatherAPIGateway creates a new instance of MockWeatherAPIGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWeatherAPIGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWeatherAPIGateway {
	mock := &MockWeatherAPIGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWeatherAPIGateway is an autogenerated mock type for the WeatherAPIGateway type
type MockWeatherAPIGateway struct {
	mock.Mock
}

type MockWeatherAPIGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWeatherAPIGateway) EXPECT() *MockWeatherAPIGateway_Expecter {
	return &MockWeatherAPIGateway_Expecter{mock: &_m.Mock}
}

// GetWeatherByCity provides a mock function for the type MockWeatherAPIGateway
func (_mock *MockWeatherAPIGateway) GetWeatherByCity(ctx context.Context, city string) (*weather.Weather, error) {
	ret := _mock.Called(ctx, city)

	if len(ret) == 0 {
		panic("no return value specified for GetWeatherByCity")
	}

	var r0 *weather.Weather
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*weather.Weather, error)); ok {
		return returnFunc(ctx, city)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *weather.Weather); ok {
		r0 = returnFunc(ctx, city)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*weather.Weather)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, city)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWeatherAPIGateway_GetWeatherByCity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWeatherByCity'
type MockWeatherAPIGateway_GetWeatherByCity_Call struct {
	*mock.Call
}

// GetWeatherByCity is a helper method to define mock.On call
//   - ctx context.Context
//   - city string
func (_e *MockWeatherAPIGateway_Expecter) GetWeatherByCity(ctx interface{}, city interface{}) *MockWeatherAPIGateway_GetWeatherByCity_Call {
	return &MockWeatherAPIGateway_GetWeatherByCity_Call{Call: _e.mock.On("GetWeatherByCity", ctx, city)}
}

func (_c *MockWeatherAPIGateway_GetWeatherByCity_Call) Run(run func(ctx context.Context, city string)) *MockWeatherAPIGateway_GetWeatherByCity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWeatherAPIGateway_GetWeatherByCity_Call) Return(weather1 *weather.Weather, err error) *MockWeatherAPIGateway_GetWeatherByCity_Call {
	_c.Call.Return(weather1, err)
	return _c
}

func (_c *MockWeatherAPIGateway_GetWeatherByCity_Call) RunAndReturn(run func(ctx context.Context, city string) (*weather.Weather, error)) *MockWeatherAPIGateway_GetWeatherByCity_Call {
	_c.Call.Return(run)
	return _c
}
